apiVersion: v1
kind: Namespace
metadata:
  name: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
spec:
  selector:
    app: minio
  ports:
    - name: http
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - server
            - /data
          env:
            - name: MINIO_ACCESS_KEY
              value: "minioadmin"
            - name: MINIO_SECRET_KEY
              value: "minioadmin"
            - name: MINIO_BUCKET
              value: "sbom"
            - name: MINIO_CONSOLE_ADDRESS
              value: ":9001"
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          emptyDir: {}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-sbom-bucket
  namespace: minio
  labels:
    app: minio
    job: create-sbom-bucket
spec:
  template:
    spec:
      containers:
        - name: mc
          image: minio/mc:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              for i in $(seq 1 10); do
                mc alias set myminio http://minio:9000 minioadmin minioadmin && \
                mc mb myminio/sbom && \
                echo "Bucket 'sbom' created successfully" && \
                exit 0 || \
                echo "Attempt $i failed, retrying in 3 seconds..." && \
                sleep 3;
              done;
              echo "Failed to create bucket 'sbom' after 10 attempts";
              exit 1;
      restartPolicy: Never
  backoffLimit: 4
